### ISSUE TITLE
Add detailed doc file describing how run and deploy programs in C#

### ISSUE THREAD

**Issue by vovapolu** [expload/pravda#236] opened 2018-09-26 08:35 UTC

**Comment by vovapolu** [comment] 2018-11-22 13:32
https://github.com/expload/pravda/blob/master/doc/dev/add-new-functionality-dotnet.md

**Comment by vovapolu** [comment] 2018-11-22 13:33
@UnimaginaryUnit ping

**Comment by UnimaginaryUnit** [comment] 2019-01-09 11:24
Duplicate of #345

**Closed** 2019-01-09 11:24 UTC
Labels: doc
